"""Radiation input contracts and analytical checks for body-fitted CFD.

This module deliberately contains no switch that enables radiation for a
field/project case.  The current DXF/OCC pipeline does not yet preserve the
separate enclosure surfaces, material evidence, or opening radiation
boundaries required for a design claim.  It provides the small, deterministic
contract used by the serial view-factor benchmark that must pass first.
"""

from __future__ import annotations

import json
import math
from numbers import Real
from pathlib import Path
import hashlib
import re


STEFAN_BOLTZMANN_W_M2_K4 = 5.670374419e-8
_TWO_PLATE_REFERENCE_PATH = (
    Path(__file__).resolve().parent / "cfd_benchmarks" / "radiation" / "two_plate" / "reference.json"
)
TWO_PLATE_CASE_CONTRACT = "two_plate_view_factor_case.v1"
RADIATION_MANIFEST_CONTRACT = "radiation_manifest.v1"

# These files are inputs generated by this module, not OpenFOAM result files.
# The benchmark input records their hashes so collection fails closed if a case
# is edited between generation and evidence collection.
_TWO_PLATE_SOURCE_PATHS = (
    "0/T",
    "0/U",
    "0/alphat",
    "0/k",
    "0/nut",
    "0/omega",
    "0/p_rgh",
    "0/qr",
    "Allrun.serial",
    "constant/boundaryRadiationProperties",
    "constant/g",
    "constant/radiationProperties",
    "constant/transportProperties",
    "constant/turbulenceProperties",
    "constant/viewFactorsDict",
    "system/blockMeshDict",
    "system/controlDict",
    "system/fvSchemes",
    "system/fvSolution",
)

# One cell is deliberate: the benchmark tests the view-factor/radiation
# evidence chain, not a flow solution.  Each named wall corresponds to one
# face in the generated mesh, allowing F to be audited deterministically.
_TWO_PLATE_PATCHES = (
    {
        "name": "hot_plate",
        "area_m2": 1.0,
        "temperature_k": 400.0,
        "emissivity": 0.8,
        "role": "reference_hot_plate",
    },
    {
        "name": "cold_plate",
        "area_m2": 1.0,
        "temperature_k": 300.0,
        "emissivity": 0.8,
        "role": "reference_cold_plate",
    },
    {
        "name": "side_xmin",
        "area_m2": 0.01,
        "temperature_k": 300.0,
        "emissivity": 0.8,
        "role": "closure_wall",
    },
    {
        "name": "side_xmax",
        "area_m2": 0.01,
        "temperature_k": 300.0,
        "emissivity": 0.8,
        "role": "closure_wall",
    },
    {
        "name": "side_ymin",
        "area_m2": 0.01,
        "temperature_k": 300.0,
        "emissivity": 0.8,
        "role": "closure_wall",
    },
    {
        "name": "side_ymax",
        "area_m2": 0.01,
        "temperature_k": 300.0,
        "emissivity": 0.8,
        "role": "closure_wall",
    },
)


class RadiationInputError(ValueError):
    """Raised when an enclosure is not evidenced well enough for radiation."""


def _sha256(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _positive_number(value, label):
    if not isinstance(value, Real) or isinstance(value, bool) or not math.isfinite(value):
        raise RadiationInputError(f"{label} 값은 유한한 숫자여야 합니다.")
    if value <= 0:
        raise RadiationInputError(f"{label} 값은 0보다 커야 합니다.")
    return float(value)


def _emissivity(value, label):
    value = _positive_number(value, label)
    if value > 1:
        raise RadiationInputError(f"{label} 값은 1 이하여야 합니다.")
    return value


def validate_radiation_input(*, engine, surfaces):
    """Validate the minimum evidence for a closed body-fitted enclosure.

    The returned records are copies, so callers can safely serialize the
    validation evidence without mutating an import manifest.  This validates
    *input readiness*, not an OpenFOAM result or a design decision.
    """
    if not isinstance(engine, str) or not engine.startswith("body_fitted"):
        raise RadiationInputError(
            "복사 해석은 검증된 body-fitted enclosure에서만 사용할 수 있습니다."
        )
    if not isinstance(surfaces, (list, tuple)):
        raise RadiationInputError("복사 표면 목록이 필요합니다.")

    participating = []
    for raw in surfaces:
        if not isinstance(raw, dict):
            raise RadiationInputError("복사 표면은 객체여야 합니다.")
        if raw.get("participating") is not True:
            continue
        name = str(raw.get("name") or "").strip()
        patch = str(raw.get("mesh_patch_name") or "").strip()
        if not name or not patch:
            raise RadiationInputError("복사 표면에는 name과 mesh_patch_name이 필요합니다.")
        material_source = str(raw.get("material_source") or "").strip()
        if not material_source:
            raise RadiationInputError(f"복사 표면 {name}에 재질 출처가 없습니다.")
        boundary = raw.get("thermal_boundary")
        if not isinstance(boundary, dict) or not str(boundary.get("type") or "").strip():
            raise RadiationInputError(f"복사 표면 {name}에 열경계 조건이 없습니다.")
        participating.append({
            "name": name,
            "mesh_patch_name": patch,
            "role": str(raw.get("role") or "wall"),
            "emissivity": _emissivity(raw.get("emissivity"), f"복사 표면 {name} 방사율"),
            "material_source": material_source,
            "thermal_boundary": dict(boundary),
        })

    if len(participating) < 2:
        raise RadiationInputError("밀폐 복사 enclosure에는 최소 2개의 참여 표면이 필요합니다.")
    names = [item["name"] for item in participating]
    if len(set(names)) != len(names):
        raise RadiationInputError("참여 복사 표면 name이 중복되었습니다.")
    patches = [item["mesh_patch_name"] for item in participating]
    if len(set(patches)) != len(patches):
        raise RadiationInputError(
            "복사 표면은 서로 분리된 mesh patch여야 합니다. 단일 wall patch로는 복사를 활성화할 수 없습니다."
        )
    return participating


def two_plate_net_flux_w_m2(*, hot_temperature_k, cold_temperature_k,
                             hot_emissivity, cold_emissivity):
    """Return signed diffuse-grey net radiative heat flux for two infinite plates."""
    hot_temperature_k = _positive_number(hot_temperature_k, "고온 표면 온도")
    cold_temperature_k = _positive_number(cold_temperature_k, "저온 표면 온도")
    hot_emissivity = _emissivity(hot_emissivity, "고온 표면 방사율")
    cold_emissivity = _emissivity(cold_emissivity, "저온 표면 방사율")
    resistance = (1.0 / hot_emissivity) + (1.0 / cold_emissivity) - 1.0
    return STEFAN_BOLTZMANN_W_M2_K4 * (
        hot_temperature_k ** 4 - cold_temperature_k ** 4
    ) / resistance


def load_two_plate_reference(path=None):
    """Load and validate the analytical two-plate benchmark reference.

    This is a benchmark input/evidence artifact, not a result from the local
    OpenFOAM installation.  A generated solver result must be compared to it
    before a view-factor configuration can be promoted beyond the benchmark.
    """
    source = Path(path) if path is not None else _TWO_PLATE_REFERENCE_PATH
    try:
        reference = json.loads(source.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RadiationInputError(f"두 평행판 복사 benchmark 기준값을 읽지 못했습니다: {exc}") from exc
    if reference.get("contract") != "radiation_benchmark_reference.v1":
        raise RadiationInputError("두 평행판 복사 benchmark 계약 버전이 올바르지 않습니다.")
    inputs = reference.get("input")
    expected = reference.get("expected")
    if not isinstance(inputs, dict) or not isinstance(expected, dict):
        raise RadiationInputError("두 평행판 복사 benchmark 입력 또는 기준값이 없습니다.")
    calculated = two_plate_net_flux_w_m2(
        hot_temperature_k=inputs.get("hot_temperature_k"),
        cold_temperature_k=inputs.get("cold_temperature_k"),
        hot_emissivity=inputs.get("hot_emissivity"),
        cold_emissivity=inputs.get("cold_emissivity"),
    )
    stored = _positive_number(expected.get("net_flux_w_m2"), "두 평행판 기준 열유속")
    if not math.isclose(calculated, stored, rel_tol=1e-9, abs_tol=1e-9):
        raise RadiationInputError(
            "두 평행판 복사 benchmark 기준값이 폐쇄형 해와 일치하지 않습니다."
        )
    return reference


def benchmark_reference_sha256(path=None):
    """Return the exact reference artifact identity required by a radiation run."""
    source = Path(path) if path is not None else _TWO_PLATE_REFERENCE_PATH
    try:
        return _sha256(source)
    except OSError as exc:
        raise RadiationInputError(f"두 평행판 복사 benchmark 해시를 계산하지 못했습니다: {exc}") from exc


def _nonnegative_number(value, label):
    if not isinstance(value, Real) or isinstance(value, bool) or not math.isfinite(value):
        raise RadiationInputError(f"{label} 값은 유한한 숫자여야 합니다.")
    if value < 0:
        raise RadiationInputError(f"{label} 값은 0 이상이어야 합니다.")
    return float(value)


def validate_radiation_manifest(manifest, *, thermal_input_sha256,
                                reference_path=None, case_dir=None):
    """Validate a serial two-plate benchmark from actual solver artifacts.

    Field/project radiation validation is intentionally unavailable. The
    standalone benchmark must be re-collected from its F and non-initial-time
    qr artifacts before its JSON summary can be accepted.
    """
    if not isinstance(manifest, dict):
        raise RadiationInputError("radiation manifest가 없습니다.")
    if case_dir is None:
        raise RadiationInputError(
            "A benchmark case_dir is required; a copied radiation JSON is not evidence."
        )
    if thermal_input_sha256 is not None:
        raise RadiationInputError(
            "Field/project thermal input cannot use the benchmark-only radiation contract."
        )
    if manifest.get("contract") != "radiation_manifest.v1":
        raise RadiationInputError("radiation manifest 계약 버전이 올바르지 않습니다.")
    if manifest.get("status") != "PASS":
        raise RadiationInputError("radiation manifest가 PASS 상태가 아닙니다.")
    if manifest.get("scope") != "serial_two_plate_view_factor_benchmark_only":
        raise RadiationInputError("Only the serial two-plate benchmark scope is supported.")
    if manifest.get("design_ready") is not False:
        raise RadiationInputError("A benchmark radiation manifest must never be design_ready.")
    if manifest.get("citation_status") != "BENCHMARK_ONLY":
        raise RadiationInputError("A benchmark radiation manifest must be BENCHMARK_ONLY.")
    if manifest.get("thermal_input_sha256") is not None:
        raise RadiationInputError("A benchmark radiation manifest cannot claim a field thermal input.")
    collected = collect_two_plate_view_factor_evidence(
        case_dir, reference_path=reference_path
    )
    if collected.get("status") != "PASS" or collected != manifest:
        raise RadiationInputError(
            "Radiation manifest does not match a fresh collection of F/qr benchmark evidence."
        )
    if manifest.get("benchmark_reference_sha256") != benchmark_reference_sha256(reference_path):
        raise RadiationInputError("radiation manifest의 benchmark 기준값 해시가 일치하지 않습니다.")

    reference = load_two_plate_reference(reference_path)
    acceptance = reference.get("acceptance") if isinstance(reference, dict) else {}
    factors = manifest.get("view_factors")
    if not isinstance(factors, dict) or factors.get("ok") is not True:
        raise RadiationInputError("view-factor 폐합/상호성 검증이 PASS가 아닙니다.")
    if _nonnegative_number(
            factors.get("max_row_sum_error"), "view-factor 행 폐합 오차"
    ) > float(acceptance["view_factor_row_sum_tolerance"]):
        raise RadiationInputError("view-factor 행 폐합 오차가 benchmark 허용범위를 넘었습니다.")
    if _nonnegative_number(
            factors.get("max_reciprocity_error_m2"), "view-factor 상호성 오차"
    ) > float(acceptance["view_factor_reciprocity_tolerance_m2"]):
        raise RadiationInputError("view-factor 상호성 오차가 benchmark 허용범위를 넘었습니다.")

    balance = manifest.get("energy_balance")
    if not isinstance(balance, dict):
        raise RadiationInputError("복사 에너지수지 증적이 없습니다.")
    if _nonnegative_number(
            balance.get("internal_radiation_balance_relative_error"), "내부 복사 에너지수지 오차"
    ) > float(acceptance["internal_radiation_balance_relative_error_max"]):
        raise RadiationInputError("내부 복사 에너지수지 오차가 benchmark 허용범위를 넘었습니다.")

    fields = manifest.get("fields")
    if not isinstance(fields, dict) or fields.get("qr_nonzero") is not True:
        raise RadiationInputError("복사 열유속 qr의 비영 증적이 없습니다.")
    patch_powers = manifest.get("patch_net_radiation_power_w")
    if not isinstance(patch_powers, dict) or len(patch_powers) < 2:
        raise RadiationInputError("패치별 순복사열 적분 증적이 충분하지 않습니다.")
    values = []
    for name, value in patch_powers.items():
        if not isinstance(name, str) or not name.strip():
            raise RadiationInputError("패치별 순복사열 적분의 패치명이 올바르지 않습니다.")
        values.append(_nonnegative_number(abs(value) if isinstance(value, Real) else value,
                                          "패치별 순복사열"))
    gross_power = sum(values)
    if gross_power <= 0:
        raise RadiationInputError("패치별 순복사열 적분이 모두 0입니다.")
    signed_total = sum(float(value) for value in patch_powers.values())
    calculated_balance_error = abs(signed_total) / gross_power
    if calculated_balance_error > float(acceptance["internal_radiation_balance_relative_error_max"]):
        raise RadiationInputError("패치별 순복사열 적분의 내부 수지가 허용범위를 넘었습니다.")
    output = dict(manifest)
    output["validated_for_benchmark"] = True
    output["computed_patch_radiation_balance_relative_error"] = calculated_balance_error
    return output


def view_factor_diagnostics(*, areas_m2, view_factors, tolerance=1e-6):
    """Check enclosure view-factor closure and reciprocity without a solver."""
    if not isinstance(areas_m2, (list, tuple)) or not areas_m2:
        raise RadiationInputError("view-factor 면적 목록이 필요합니다.")
    areas = [_positive_number(area, "표면 면적") for area in areas_m2]
    size = len(areas)
    if not isinstance(view_factors, (list, tuple)) or len(view_factors) != size:
        raise RadiationInputError("view-factor 행 수가 표면 수와 일치해야 합니다.")
    if not isinstance(tolerance, Real) or isinstance(tolerance, bool) or tolerance < 0:
        raise RadiationInputError("view-factor 허용오차가 올바르지 않습니다.")

    matrix = []
    for row in view_factors:
        if not isinstance(row, (list, tuple)) or len(row) != size:
            raise RadiationInputError("각 view-factor 행은 표면 수만큼의 값을 가져야 합니다.")
        clean_row = []
        for factor in row:
            if (not isinstance(factor, Real) or isinstance(factor, bool)
                    or not math.isfinite(factor) or factor < 0):
                raise RadiationInputError("view-factor는 0 이상의 유한한 숫자여야 합니다.")
            clean_row.append(float(factor))
        matrix.append(clean_row)

    row_errors = [abs(sum(row) - 1.0) for row in matrix]
    reciprocity_errors = [
        abs(areas[i] * matrix[i][j] - areas[j] * matrix[j][i])
        for i in range(size) for j in range(i + 1, size)
    ]
    max_row_sum_error = max(row_errors, default=0.0)
    max_reciprocity_error = max(reciprocity_errors, default=0.0)
    errors = []
    if max_row_sum_error > tolerance:
        errors.append("VIEW_FACTOR_ROW_CLOSURE")
    if max_reciprocity_error > tolerance:
        errors.append("VIEW_FACTOR_RECIPROCITY")
    return {
        "contract": "view_factor_diagnostics.v1",
        "ok": not errors,
        "surface_count": size,
        "tolerance": float(tolerance),
        "max_row_sum_error": max_row_sum_error,
        "max_reciprocity_error_m2": max_reciprocity_error,
        "errors": errors,
    }


def _foam_header(class_name, object_name, location):
    """Return a small deterministic OpenFOAM dictionary header."""
    return (
        "/*--------------------------------*- C++ -*----------------------------------*\\\n"
        "| MEP CFD Studio: serial view-factor benchmark input                         |\n"
        "\\*---------------------------------------------------------------------------*/\n"
        "FoamFile\n{\n"
        "    version     2.0;\n"
        "    format      ascii;\n"
        f"    class       {class_name};\n"
        f"    location    \"{location}\";\n"
        f"    object      {object_name};\n"
        "}\n"
        "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //\n\n"
    )


def _write_text(path, text):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def _write_json(path, payload):
    _write_text(path, json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n")


def _two_plate_block_mesh_dict():
    return _foam_header("dictionary", "blockMeshDict", "system") + """convertToMeters 1;

vertices
(
    (0 0 0)
    (1 0 0)
    (1 1 0)
    (0 1 0)
    (0 0 0.01)
    (1 0 0.01)
    (1 1 0.01)
    (0 1 0.01)
);

blocks
(
    hex (0 1 2 3 4 5 6 7) (1 1 1) simpleGrading (1 1 1)
);

edges
(
);

boundary
(
    hot_plate
    {
        type wall;
        inGroups 2(wall viewFactorWall);
        faces ((0 3 2 1));
    }
    cold_plate
    {
        type wall;
        inGroups 2(wall viewFactorWall);
        faces ((4 5 6 7));
    }
    side_xmin
    {
        type wall;
        inGroups 2(wall viewFactorWall);
        faces ((0 4 7 3));
    }
    side_xmax
    {
        type wall;
        inGroups 2(wall viewFactorWall);
        faces ((1 2 6 5));
    }
    side_ymin
    {
        type wall;
        inGroups 2(wall viewFactorWall);
        faces ((0 1 5 4));
    }
    side_ymax
    {
        type wall;
        inGroups 2(wall viewFactorWall);
        faces ((3 7 6 2));
    }
);

mergePatchPairs
(
);
"""


def _two_plate_radiation_properties():
    return _foam_header("dictionary", "radiationProperties", "constant") + """radiationModel  viewFactor;

viewFactorCoeffs
{
    useSolarLoad   false;
}

solverFreq              1;
firstIter               true;
absorptionEmissionModel none;
scatterModel            none;
sootModel               none;
"""


def _two_plate_boundary_radiation_properties():
    entries = []
    for patch in _TWO_PLATE_PATCHES:
        entries.append(
            f"{patch['name']}\n{{\n"
            "    type        opaqueDiffusive;\n"
            f"    emissivity  uniform {patch['emissivity']:.12g};\n"
            "}\n"
        )
    return (
        _foam_header("dictionary", "boundaryRadiationProperties", "constant")
        + "\n".join(entries)
    )


def _two_plate_view_factors_dict():
    # createViewFactors is the current OpenCFD workflow; the source itself is
    # intentionally not executed by this generator.
    return _foam_header("dictionary", "viewFactorsDict", "constant") + """raySearchEngine  voxel;
agglomerate      false;
nRayPerFace      1;
writeViewFactors true;
writeRays        false;
"""


def _wall_entries(field_type, value, *, extra=""):
    entries = []
    for patch in _TWO_PLATE_PATCHES:
        entries.append(
            f"    {patch['name']}\n    {{\n"
            f"        type            {field_type};\n"
            f"        {extra}"
            f"        value           uniform {value};\n"
            "    }\n"
        )
    return "".join(entries)


def _two_plate_temperature_field():
    entries = []
    for patch in _TWO_PLATE_PATCHES:
        entries.append(
            f"    {patch['name']}\n    {{\n"
            "        type            fixedValue;\n"
            f"        value           uniform {patch['temperature_k']:.12g};\n"
            "    }\n"
        )
    return (
        _foam_header("volScalarField", "T", "0")
        + "dimensions      [0 0 0 1 0 0 0];\n"
        + "internalField   uniform 300;\n\n"
        + "boundaryField\n{\n"
        + "".join(entries)
        + "}\n"
    )


def _two_plate_qr_field():
    entries = []
    for patch in _TWO_PLATE_PATCHES:
        entries.append(
            f"    {patch['name']}\n    {{\n"
            "        type            greyDiffusiveRadiationViewFactor;\n"
            "        qro             uniform 0;\n"
            "        value           uniform 0;\n"
            "    }\n"
        )
    return (
        _foam_header("volScalarField", "qr", "0")
        + "dimensions      [1 0 -3 0 0 0 0];\n"
        + "internalField   uniform 0;\n\n"
        + "boundaryField\n{\n"
        + "".join(entries)
        + "}\n"
    )


def _two_plate_scalar_field(name, dimensions, internal_value, field_type, value,
                            *, extra=""):
    return (
        _foam_header("volScalarField", name, "0")
        + f"dimensions      {dimensions};\n"
        + f"internalField   uniform {internal_value};\n\n"
        + "boundaryField\n{\n"
        + _wall_entries(field_type, value, extra=extra)
        + "}\n"
    )


def _two_plate_vector_field(name, dimensions, internal_value, field_type, value):
    return (
        _foam_header("volVectorField", name, "0")
        + f"dimensions      {dimensions};\n"
        + f"internalField   uniform {internal_value};\n\n"
        + "boundaryField\n{\n"
        + _wall_entries(field_type, value)
        + "}\n"
    )


def _two_plate_transport_properties():
    return _foam_header("dictionary", "transportProperties", "constant") + """transportModel  Newtonian;
nu              1.5e-05;
beta            0.00333333333333;
TRef            300;
Pr              0.71;
Prt             0.85;
"""


def _two_plate_gravity():
    return _foam_header("uniformDimensionedVectorField", "g", "constant") + """dimensions [0 1 -2 0 0 0 0];
value      (0 0 0);
"""


def _two_plate_turbulence_properties():
    return _foam_header("dictionary", "turbulenceProperties", "constant") + """simulationType RAS;

RAS
{
    RASModel        kOmegaSST;
    turbulence      on;
    printCoeffs     on;
}
"""


def _two_plate_control_dict():
    return _foam_header("dictionary", "controlDict", "system") + """application     buoyantBoussinesqPimpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         1;
deltaT          0.1;
writeControl    timeStep;
writeInterval   1;
purgeWrite      0;
writeFormat     ascii;
writePrecision  12;
timeFormat      general;
timePrecision   12;
runTimeModifiable true;
adjustTimeStep  no;
maxCo           1;
"""


def _two_plate_fv_schemes():
    return _foam_header("dictionary", "fvSchemes", "system") + """ddtSchemes
{
    default Euler;
}
gradSchemes
{
    default Gauss linear;
}
divSchemes
{
    default none;
    div(phi,U) Gauss upwind;
    div(phi,T) Gauss upwind;
    div(phi,k) Gauss upwind;
    div(phi,omega) Gauss upwind;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes
{
    default Gauss linear corrected;
}
interpolationSchemes
{
    default linear;
}
snGradSchemes
{
    default corrected;
}
"""


def _two_plate_fv_solution():
    return _foam_header("dictionary", "fvSolution", "system") + """solvers
{
    p_rgh
    {
        solver          PCG;
        preconditioner  DIC;
        tolerance       1e-8;
        relTol          0;
    }
    "(U|T|k|omega)"
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-8;
        relTol          0;
    }
}

PIMPLE
{
    nOuterCorrectors         1;
    nCorrectors              2;
    nNonOrthogonalCorrectors 0;
}

relaxationFactors
{
    fields
    {
        p_rgh 0.3;
    }
    equations
    {
        ".*" 0.7;
    }
}
"""


def _two_plate_allrun():
    return """#!/bin/sh
# This script is intentionally serial only.  The generator never executes it.
set -eu

blockMesh > log.blockMesh 2>&1
createViewFactors > log.createViewFactors 2>&1
buoyantBoussinesqPimpleFoam > log.buoyantBoussinesqPimpleFoam 2>&1
"""


def _two_plate_run_notes():
    return """# Serial two-plate view-factor benchmark

This directory is a **benchmark input**, not a completed OpenFOAM result and
not a field/project radiation case.  It intentionally has no MPI command.

For an OpenCFD OpenFOAM v2606 installation, run Allrun.serial from this case
directory only after checking the local executable names and the generated
dictionary syntax against that installation.  The expected serial stages are:

1. blockMesh
2. createViewFactors (writes constant/F and related view-factor artifacts)
3. buoyantBoussinesqPimpleFoam (writes a non-initial-time qr field)

Then run the MEP CFD Studio collector.  It will create radiation_manifest.json
only from actual constant/F and a non-initial-time qr output.  Missing,
incomplete, or source-mismatched artifacts remain NOT_EVALUATED; a benchmark
PASS does not enable radiation for DXF/OCC or project cases.
"""


def build_two_plate_view_factor_case(case_dir, *, reference_path=None):
    """Generate a deterministic, serial-only OpenFOAM view-factor benchmark.

    No OpenFOAM executable is invoked here.  The generated case uses the
    v2606-documented createViewFactors workflow and is deliberately kept
    outside cfd_physics.build_buoyant_case so field/project cases cannot
    accidentally activate radiation.
    """
    case = Path(case_dir).expanduser().resolve()
    if case.exists() and not case.is_dir():
        raise RadiationInputError("두 평행판 benchmark 경로는 디렉터리여야 합니다.")
    field_case_markers = ("thermal_input.json", "mesh_manifest.json", "surface_manifest.json")
    if any((case / marker).is_file() for marker in field_case_markers):
        raise RadiationInputError(
            "두 평행판 복사 benchmark는 standalone 디렉터리에만 생성할 수 있습니다. "
            "현장/project body-fitted case에는 복사를 추가하지 않습니다."
        )
    if case.exists() and any(case.iterdir()):
        raise RadiationInputError(
            "Two-plate benchmark generation requires a new or empty directory; "
            "an existing OpenFOAM case will not be overwritten."
        )
    reference = load_two_plate_reference(reference_path)
    reference_file = Path(reference_path) if reference_path is not None else _TWO_PLATE_REFERENCE_PATH
    case.mkdir(parents=True, exist_ok=True)

    files = {
        "system/blockMeshDict": _two_plate_block_mesh_dict(),
        "constant/radiationProperties": _two_plate_radiation_properties(),
        "constant/boundaryRadiationProperties": _two_plate_boundary_radiation_properties(),
        "constant/viewFactorsDict": _two_plate_view_factors_dict(),
        "constant/transportProperties": _two_plate_transport_properties(),
        "constant/g": _two_plate_gravity(),
        "constant/turbulenceProperties": _two_plate_turbulence_properties(),
        "system/controlDict": _two_plate_control_dict(),
        "system/fvSchemes": _two_plate_fv_schemes(),
        "system/fvSolution": _two_plate_fv_solution(),
        "0/T": _two_plate_temperature_field(),
        "0/qr": _two_plate_qr_field(),
        "0/U": _two_plate_vector_field(
            "U", "[0 1 -1 0 0 0 0]", "(0 0 0)", "fixedValue", "(0 0 0)"
        ),
        "0/p_rgh": _two_plate_scalar_field(
            "p_rgh", "[0 2 -2 0 0 0 0]", "0", "fixedFluxPressure", "0"
        ),
        "0/k": _two_plate_scalar_field(
            "k", "[0 2 -2 0 0 0 0]", "1e-06", "kqRWallFunction", "1e-06"
        ),
        "0/omega": _two_plate_scalar_field(
            "omega", "[0 0 -1 0 0 0 0]", "1", "omegaWallFunction", "1"
        ),
        "0/nut": _two_plate_scalar_field(
            "nut", "[0 2 -1 0 0 0 0]", "0", "nutkWallFunction", "0"
        ),
        "0/alphat": _two_plate_scalar_field(
            "alphat", "[0 2 -1 0 0 0 0]", "0", "alphatWallFunction", "0"
        ),
        "Allrun.serial": _two_plate_allrun(),
        "RUN_SERIAL_ONLY.md": _two_plate_run_notes(),
    }
    for relative, text in files.items():
        _write_text(case / relative, text)

    source_hashes = {relative: _sha256(case / relative) for relative in _TWO_PLATE_SOURCE_PATHS}
    benchmark_input = {
        "schema_version": 1,
        "contract": TWO_PLATE_CASE_CONTRACT,
        "scope": "serial_two_plate_view_factor_benchmark_only",
        "execution_mode": "serial_only",
        "openfoam_target": "OpenCFD OpenFOAM v2606 dictionary workflow; not runtime-verified",
        "solver": "buoyantBoussinesqPimpleFoam",
        "view_factor_utility": "createViewFactors",
        "reference_sha256": _sha256(reference_file),
        "reference_contract": reference["contract"],
        "patches": [dict(item) for item in _TWO_PLATE_PATCHES],
        "view_factor_matrix": {
            "surface_order": [item["name"] for item in _TWO_PLATE_PATCHES],
            "areas_m2": [item["area_m2"] for item in _TWO_PLATE_PATCHES],
        },
        "source_hashes": source_hashes,
    }
    _write_json(case / "radiation_benchmark_input.json", benchmark_input)
    return {
        "contract": TWO_PLATE_CASE_CONTRACT,
        "case_dir": str(case),
        "execution_mode": "serial_only",
        "source_hashes": source_hashes,
        "reference_sha256": benchmark_input["reference_sha256"],
    }


def _strip_foam_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return re.sub(r"//[^\n]*", "", text)


def _balanced_braces(text, opening_index):
    if opening_index >= len(text) or text[opening_index] != "{":
        raise RadiationInputError("OpenFOAM dictionary 중괄호를 찾지 못했습니다.")
    depth = 0
    for index in range(opening_index, len(text)):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[opening_index + 1:index], index + 1
    raise RadiationInputError("OpenFOAM dictionary 중괄호가 닫히지 않았습니다.")


def _parse_foam_parenthesized_list(text, opening_index):
    """Parse the scalar-list subset emitted by createViewFactors F output."""
    if text[opening_index] != "(":
        raise RadiationInputError("view-factor 행렬 목록이 없습니다.")
    values = []
    index = opening_index + 1
    while True:
        while index < len(text) and text[index].isspace():
            index += 1
        if index >= len(text):
            raise RadiationInputError("view-factor 행렬 목록이 닫히지 않았습니다.")
        if text[index] == ")":
            return values, index + 1
        if text[index] == "(":
            nested, index = _parse_foam_parenthesized_list(text, index)
            values.append(nested)
            continue
        match = re.match(r"[^\s()]+", text[index:])
        if match is None:
            raise RadiationInputError("view-factor 행렬 토큰을 읽지 못했습니다.")
        token = match.group(0)
        index += len(token)
        while index < len(text) and text[index].isspace():
            index += 1
        # Some OpenFOAM list writers emit a count immediately before a nested
        # list (for example 6(...)). Validate and discard that count.
        if index < len(text) and text[index] == "(":
            try:
                declared = int(token)
            except ValueError as exc:
                raise RadiationInputError("view-factor 목록 길이가 올바르지 않습니다.") from exc
            nested, index = _parse_foam_parenthesized_list(text, index)
            if len(nested) != declared:
                raise RadiationInputError("view-factor 목록 길이와 선언값이 다릅니다.")
            values.append(nested)
            continue
        try:
            number = float(token)
        except ValueError as exc:
            raise RadiationInputError("view-factor 행렬에 숫자가 아닌 값이 있습니다.") from exc
        if not math.isfinite(number):
            raise RadiationInputError("view-factor 행렬에 유한하지 않은 값이 있습니다.")
        values.append(number)


def _parse_view_factor_matrix(path):
    try:
        text = _strip_foam_comments(Path(path).read_text(encoding="utf-8"))
    except OSError as exc:
        raise RadiationInputError(f"view-factor 행렬을 읽지 못했습니다: {exc}") from exc
    # Skip the FoamFile header, whose version number must never be mistaken for
    # the matrix size.
    header = re.search(r"\bFoamFile\s*\{", text)
    body_start = 0
    if header is not None:
        _, body_start = _balanced_braces(text, text.find("{", header.start()))
    match = re.search(r"\b(\d+)\s*\(", text[body_start:])
    if match is None:
        raise RadiationInputError("view-factor 행렬 차원을 찾지 못했습니다.")
    declared_rows = int(match.group(1))
    opening = body_start + match.end() - 1
    rows, _ = _parse_foam_parenthesized_list(text, opening)
    if len(rows) != declared_rows:
        raise RadiationInputError("view-factor 행렬 행 수와 선언값이 다릅니다.")
    matrix = []
    for row in rows:
        if not isinstance(row, list) or len(row) != declared_rows:
            raise RadiationInputError("view-factor 행렬이 정사각 행렬이 아닙니다.")
        if any(not isinstance(value, float) for value in row):
            raise RadiationInputError("view-factor 행렬 행에 숫자 이외의 값이 있습니다.")
        matrix.append(row)
    return matrix


def _parse_qr_patch_values(path):
    """Read means of the scalar value entries from a written qr field."""
    try:
        text = _strip_foam_comments(Path(path).read_text(encoding="utf-8"))
    except OSError as exc:
        raise RadiationInputError(f"qr field를 읽지 못했습니다: {exc}") from exc
    boundary = re.search(r"\bboundaryField\s*\{", text)
    if boundary is None:
        raise RadiationInputError("qr field에 boundaryField가 없습니다.")
    content, _ = _balanced_braces(text, text.find("{", boundary.start()))
    values = {}
    position = 0
    while True:
        patch = re.search(r"([A-Za-z_][A-Za-z0-9_]*)\s*\{", content[position:])
        if patch is None:
            break
        name = patch.group(1)
        opening = position + patch.end() - 1
        patch_content, position = _balanced_braces(content, opening)
        uniform = re.search(
            r"\bvalue\s+uniform\s+([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)\s*;",
            patch_content,
        )
        if uniform is not None:
            values[name] = float(uniform.group(1))
            continue
        nonuniform = re.search(
            r"\bvalue\s+nonuniform\s+(?:List<scalar>\s*)?(?:\d+\s*)?\((.*?)\)\s*;",
            patch_content,
            flags=re.DOTALL,
        )
        if nonuniform is None:
            continue
        numbers = [
            float(token) for token in re.findall(
                r"[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?",
                nonuniform.group(1),
            )
        ]
        if not numbers or not all(math.isfinite(value) for value in numbers):
            raise RadiationInputError(f"qr patch {name}의 값이 비어 있거나 유한하지 않습니다.")
        values[name] = math.fsum(numbers) / len(numbers)
    if not values:
        raise RadiationInputError("qr field의 patch 값을 읽지 못했습니다.")
    return values


def _latest_solver_qr(case):
    candidates = []
    for child in Path(case).iterdir():
        if not child.is_dir():
            continue
        try:
            value = float(child.name)
        except ValueError:
            continue
        if math.isfinite(value) and value > 0 and (child / "qr").is_file():
            candidates.append((value, child.name, child / "qr"))
    if not candidates:
        return None
    return max(candidates, key=lambda item: item[0])


def _source_integrity(case, benchmark_input):
    expected = benchmark_input.get("source_hashes")
    if not isinstance(expected, dict) or set(expected) != set(_TWO_PLATE_SOURCE_PATHS):
        return False, ["SOURCE_HASH_CONTRACT_INVALID"], {}
    current = {}
    blockers = []
    for relative in _TWO_PLATE_SOURCE_PATHS:
        path = Path(case) / relative
        if not path.is_file():
            blockers.append(f"SOURCE_INPUT_MISSING:{relative}")
            continue
        current[relative] = _sha256(path)
        if expected.get(relative) != current[relative]:
            blockers.append(f"SOURCE_HASH_MISMATCH:{relative}")
    return not blockers, blockers, current


def _benchmark_manifest_base(case, benchmark_input, *, reference_sha256, source_hashes):
    return {
        "schema_version": 1,
        "contract": RADIATION_MANIFEST_CONTRACT,
        "scope": "serial_two_plate_view_factor_benchmark_only",
        "design_ready": False,
        "citation_status": "BENCHMARK_ONLY",
        "benchmark_case_contract": benchmark_input.get("contract"),
        "benchmark_input_sha256": _sha256(Path(case) / "radiation_benchmark_input.json"),
        "benchmark_reference_sha256": reference_sha256,
        "thermal_input_sha256": None,
        "source_hashes": source_hashes,
        "solver_outputs": {"hashes": {}},
        "fields": {"qr_available": False, "qr_nonzero": False},
        "view_factors": {"available": False, "ok": False},
        "patch_net_radiation_power_w": {},
        "energy_balance": {},
        "blockers": [],
    }


def collect_two_plate_view_factor_evidence(case_dir, *, reference_path=None):
    """Collect a serial benchmark manifest from already written OF outputs.

    This function never calls OpenFOAM and never manufactures a radiation
    result. A missing F matrix, a missing non-initial-time qr field, malformed
    field data, source drift, or a failed benchmark comparison produces a
    NOT_EVALUATED manifest instead of a PASS.
    """
    case = Path(case_dir).expanduser().resolve()
    input_path = case / "radiation_benchmark_input.json"
    try:
        benchmark_input = json.loads(input_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RadiationInputError(
            f"생성된 두 평행판 benchmark 입력을 읽지 못했습니다: {exc}"
        ) from exc
    if benchmark_input.get("contract") != TWO_PLATE_CASE_CONTRACT:
        raise RadiationInputError("두 평행판 benchmark 입력 계약 버전이 올바르지 않습니다.")
    if benchmark_input.get("execution_mode") != "serial_only":
        raise RadiationInputError("두 평행판 benchmark는 serial_only 계약이어야 합니다.")

    reference = load_two_plate_reference(reference_path)
    reference_file = (
        Path(reference_path) if reference_path is not None else _TWO_PLATE_REFERENCE_PATH
    )
    reference_sha256 = _sha256(reference_file)
    source_ok, source_blockers, source_hashes = _source_integrity(case, benchmark_input)
    manifest = _benchmark_manifest_base(
        case, benchmark_input, reference_sha256=reference_sha256, source_hashes=source_hashes
    )
    manifest["source_integrity"] = {
        "ok": source_ok,
        "expected_hashes": dict(benchmark_input.get("source_hashes") or {}),
        "observed_hashes": source_hashes,
    }
    blockers = list(source_blockers)
    if benchmark_input.get("reference_sha256") != reference_sha256:
        blockers.append("BENCHMARK_REFERENCE_HASH_MISMATCH")

    matrix_path = case / "constant" / "F"
    if not matrix_path.is_file():
        blockers.append("VIEW_FACTOR_MATRIX_MISSING")
    else:
        manifest["solver_outputs"]["hashes"]["constant/F"] = _sha256(matrix_path)
        try:
            matrix = _parse_view_factor_matrix(matrix_path)
            matrix_meta = benchmark_input.get("view_factor_matrix")
            areas = matrix_meta.get("areas_m2") if isinstance(matrix_meta, dict) else None
            if not isinstance(areas, list) or len(matrix) != len(areas):
                raise RadiationInputError("view-factor 행렬 차원이 benchmark 표면 수와 다릅니다.")
            acceptance = reference["acceptance"]
            diagnostics = view_factor_diagnostics(
                areas_m2=areas,
                view_factors=matrix,
                tolerance=max(
                    float(acceptance["view_factor_row_sum_tolerance"]),
                    float(acceptance["view_factor_reciprocity_tolerance_m2"]),
                ),
            )
            diagnostics["available"] = True
            diagnostics["source"] = "constant/F"
            manifest["view_factors"] = diagnostics
            if not diagnostics["ok"]:
                blockers.append("VIEW_FACTOR_DIAGNOSTICS_FAILED")
        except (RadiationInputError, KeyError, TypeError, ValueError):
            blockers.append("VIEW_FACTOR_MATRIX_INVALID")

    qr_output = _latest_solver_qr(case)
    if qr_output is None:
        blockers.append("QR_FIELD_MISSING")
    else:
        _, time_name, qr_path = qr_output
        relative_qr = str(qr_path.relative_to(case)).replace("\\", "/")
        manifest["solver_outputs"]["qr_time"] = time_name
        manifest["solver_outputs"]["qr_path"] = relative_qr
        manifest["solver_outputs"]["hashes"][relative_qr] = _sha256(qr_path)
        try:
            qr_values = _parse_qr_patch_values(qr_path)
            patches = benchmark_input.get("patches")
            if not isinstance(patches, list):
                raise RadiationInputError("benchmark 표면 정의가 없습니다.")
            patch_powers = {}
            for patch in patches:
                if not isinstance(patch, dict):
                    raise RadiationInputError("benchmark 표면 정의가 올바르지 않습니다.")
                name = patch.get("name")
                if not isinstance(name, str) or name not in qr_values:
                    blockers.append(f"QR_PATCH_MISSING:{name}")
                    continue
                patch_powers[name] = qr_values[name] * _positive_number(
                    patch.get("area_m2"), f"{name} 표면적"
                )
            manifest["fields"] = {
                "qr_available": True,
                "qr_nonzero": any(abs(value) > 1e-12 for value in patch_powers.values()),
                "qr_patch_mean_w_m2": {
                    name: qr_values[name] for name in patch_powers
                },
            }
            manifest["patch_net_radiation_power_w"] = patch_powers
            if len(patch_powers) != len(patches):
                blockers.append("QR_PATCH_INCOMPLETE")
            elif not manifest["fields"]["qr_nonzero"]:
                blockers.append("QR_FIELD_ZERO")
            else:
                gross = math.fsum(abs(value) for value in patch_powers.values())
                signed = math.fsum(patch_powers.values())
                balance_error = abs(signed) / gross if gross else math.inf
                manifest["energy_balance"] = {
                    "patch_net_radiation_power_w": signed,
                    "gross_patch_radiation_power_w": gross,
                    "internal_radiation_balance_relative_error": balance_error,
                }
                if balance_error > float(reference["acceptance"][
                        "internal_radiation_balance_relative_error_max"
                ]):
                    blockers.append("PATCH_RADIATION_BALANCE_FAILED")
                hot = manifest["fields"]["qr_patch_mean_w_m2"].get("hot_plate")
                cold = manifest["fields"]["qr_patch_mean_w_m2"].get("cold_plate")
                expected_flux = float(reference["expected"]["net_flux_w_m2"])
                if hot is None or cold is None or expected_flux <= 0:
                    blockers.append("REFERENCE_FLUX_EVIDENCE_MISSING")
                else:
                    expected_signs = reference["expected"].get(
                        "qr_patch_sign_convention", {}
                    )
                    direction_ok = (
                        expected_signs.get("hot_plate") == "negative"
                        and expected_signs.get("cold_plate") == "positive"
                        and hot < 0.0 and cold > 0.0
                    )
                    relative_error = max(
                        abs(abs(hot) - expected_flux) / expected_flux,
                        abs(abs(cold) - expected_flux) / expected_flux,
                    )
                    manifest["reference_comparison"] = {
                        "expected_net_flux_w_m2": expected_flux,
                        "hot_plate_qr_w_m2": hot,
                        "cold_plate_qr_w_m2": cold,
                        "expected_qr_patch_sign_convention": expected_signs,
                        "direction_ok": direction_ok,
                        "relative_error": relative_error,
                        "limit": float(reference["acceptance"]["solver_flux_relative_error_max"]),
                    }
                    if not direction_ok:
                        blockers.append("REFERENCE_FLUX_DIRECTION_INVALID")
                    if relative_error > float(
                            reference["acceptance"]["solver_flux_relative_error_max"]
                    ):
                        blockers.append("REFERENCE_FLUX_OUT_OF_TOLERANCE")
        except (RadiationInputError, KeyError, TypeError, ValueError):
            blockers.append("QR_FIELD_INVALID")

    # Deduplicate while preserving a readable, deterministic order.
    manifest["blockers"] = list(dict.fromkeys(blockers))
    manifest["status"] = "PASS" if source_ok and not manifest["blockers"] else "NOT_EVALUATED"
    manifest["benchmark_ready"] = manifest["status"] == "PASS"
    _write_json(case / "radiation_manifest.json", manifest)
    return manifest
